import { LibraryItem } from "@/components/library/library-view";

export const demoStats = {
  total: 142,
  movies: 64,
  series: 42,
  anime: 36,
  watching: 8,
  completed: 118,
  totalMinutes: 26400,
};

export const demoLibraryItems: LibraryItem[] = [
  {
    id: "demo-1",
    media: {
      id: "tmdb:movie:872585",
      source: "tmdb",
      sourceId: "872585",
      mediaType: "movie",
      title: "Oppenheimer",
      posterPath: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
      backdropPath: null,
      year: "2023",
      rating: 8.9,
      totalEpisodes: 1,
      genres: ["Drama", "History"],
    },
    status: "completed",
    userRating: "masterpiece",
    updatedAt: "2024-03-10T12:00:00.000Z",
  },
  {
    id: "demo-2",
    media: {
      id: "tmdb:movie:569094",
      source: "tmdb",
      sourceId: "569094",
      mediaType: "movie",
      title: "Spider-Man: Across the Spider-Verse",
      posterPath: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
      backdropPath: null,
      year: "2023",
      rating: 8.4,
      totalEpisodes: 1,
      genres: ["Animation", "Action", "Comedy"],
    },
    status: "completed",
    userRating: "masterpiece",
    updatedAt: "2024-02-14T15:30:00.000Z",
  },
  {
    id: "demo-3",
    media: {
      id: "tmdb:tv:95396",
      source: "tmdb",
      sourceId: "95396",
      mediaType: "series",
      title: "Severance",
      posterPath: "https://image.tmdb.org/t/p/w500/pPHpeI2X1qEd1CS1SeyrdhZ4qnT.jpg",
      backdropPath: null,
      year: "2022",
      rating: 8.4,
      totalEpisodes: 19,
      genres: ["Sci-Fi", "Mystery", "Drama"],
      status: "Returning Series",
    },
    status: "watching",
    userRating: "masterpiece",
    userEpisodes: 17,
    currentSeason: 2,
    currentEpisode: 8,
    seasons: [
      { seasonNumber: 1, name: "Season 1", episodeCount: 9 },
      { seasonNumber: 2, name: "Season 2", episodeCount: 10 },
    ],
    updatedAt: "2024-04-01T08:00:00.000Z",
  },
  {
    id: "demo-4",
    media: {
      id: "tmdb:movie:792307",
      source: "tmdb",
      sourceId: "792307",
      mediaType: "movie",
      title: "Poor Things",
      posterPath: "https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
      backdropPath: null,
      year: "2023",
      rating: 7.8,
      totalEpisodes: 1,
      genres: ["Comedy", "Sci-Fi", "Romance"],
    },
    status: "completed",
    userRating: "good",
    updatedAt: "2024-01-20T21:00:00.000Z",
  },
  {
    id: "demo-5",
    media: {
      id: "tmdb:tv:126308",
      source: "tmdb",
      sourceId: "126308",
      mediaType: "series",
      title: "Shōgun",
      posterPath: "https://image.tmdb.org/t/p/w500/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg",
      backdropPath: null,
      year: "2024",
      endYear: "2024",
      rating: 8.5,
      totalEpisodes: 10,
      genres: ["Drama", "History", "Action"],
      status: "Ended",
    },
    status: "watching",
    userRating: "great",
    userEpisodes: 7,
    currentSeason: 1,
    currentEpisode: 7,
    seasons: [{ seasonNumber: 1, name: "Season 1", episodeCount: 10 }],
    updatedAt: "2024-04-12T18:40:00.000Z",
  },
  {
    id: "demo-6",
    media: {
      id: "tmdb:tv:1429",
      source: "tmdb",
      sourceId: "1429",
      mediaType: "anime",
      title: "Attack on Titan",
      posterPath: "https://image.tmdb.org/t/p/w500/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg",
      backdropPath: null,
      year: "2013",
      endYear: "2023",
      rating: 8.7,
      totalEpisodes: 87,
      genres: ["Action", "Fantasy", "Animation"],
      status: "Ended",
    },
    status: "completed",
    userRating: "masterpiece",
    userEpisodes: 87,
    updatedAt: "2023-12-05T10:00:00.000Z",
  },
  {
    id: "demo-7",
    media: {
      id: "tmdb:tv:209867",
      source: "tmdb",
      sourceId: "209867",
      mediaType: "anime",
      title: "Frieren: Beyond Journey's End",
      posterPath: "https://image.tmdb.org/t/p/w500/dqZENchTd7lp5zht7BdlqM7RBhD.jpg",
      backdropPath: null,
      year: "2023",
      rating: 8.9,
      totalEpisodes: 28,
      genres: ["Fantasy", "Adventure", "Animation"],
    },
    status: "completed",
    userRating: "masterpiece",
    userEpisodes: 28,
    updatedAt: "2024-03-22T19:00:00.000Z",
  },
  {
    id: "demo-8",
    media: {
      id: "tmdb:tv:95479",
      source: "tmdb",
      sourceId: "95479",
      mediaType: "anime",
      title: "Jujutsu Kaisen",
      posterPath: "https://image.tmdb.org/t/p/w500/6qQzMJG27XOJsyAEEIisoJB45j2.jpg",
      backdropPath: null,
      year: "2020",
      rating: 8.6,
      totalEpisodes: 47,
      genres: ["Action", "Supernatural", "Animation"],
    },
    status: "completed",
    userRating: "great",
    userEpisodes: 47,
    updatedAt: "2024-01-15T14:00:00.000Z",
  },
  {
    id: "demo-9",
    media: {
      id: "tmdb:movie:666277",
      source: "tmdb",
      sourceId: "666277",
      mediaType: "movie",
      title: "Past Lives",
      posterPath: "https://image.tmdb.org/t/p/w500/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg",
      backdropPath: null,
      year: "2023",
      rating: 7.9,
      totalEpisodes: 1,
      genres: ["Drama", "Romance"],
    },
    status: "completed",
    userRating: "good",
    updatedAt: "2023-11-20T22:15:00.000Z",
  },
  {
    id: "demo-10",
    media: {
      id: "tmdb:movie:937287",
      source: "tmdb",
      sourceId: "937287",
      mediaType: "movie",
      title: "Challengers",
      posterPath: "https://image.tmdb.org/t/p/w500/H6vke7zGiuLsz4v4RPeReb9rsv.jpg",
      backdropPath: null,
      year: "2024",
      rating: 7.2,
      totalEpisodes: 1,
      genres: ["Drama", "Romance"],
    },
    status: "completed",
    userRating: "average",
    updatedAt: "2024-05-02T16:00:00.000Z",
  },
  {
    id: "demo-11",
    media: {
      id: "tmdb:tv:85937",
      source: "tmdb",
      sourceId: "85937",
      mediaType: "anime",
      title: "Demon Slayer: Kimetsu no Yaiba",
      posterPath: "https://image.tmdb.org/t/p/w500/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg",
      backdropPath: null,
      year: "2019",
      rating: 8.7,
      totalEpisodes: 55,
      genres: ["Action", "Fantasy", "Animation"],
    },
    status: "completed",
    userRating: "good",
    userEpisodes: 55,
    updatedAt: "2024-02-28T11:00:00.000Z",
  },
  {
    id: "demo-12",
    media: {
      id: "tmdb:tv:114410",
      source: "tmdb",
      sourceId: "114410",
      mediaType: "anime",
      title: "Chainsaw Man",
      posterPath: "https://image.tmdb.org/t/p/w500/iFM1dyFi0rByvEomEkmm7NpQeeb.jpg",
      backdropPath: null,
      year: "2022",
      rating: 8.5,
      totalEpisodes: 12,
      genres: ["Action", "Supernatural", "Animation"],
    },
    status: "completed",
    userRating: "average",
    userEpisodes: 12,
    updatedAt: "2023-10-18T17:45:00.000Z",
  },
  {
    id: "demo-13",
    media: {
      id: "tmdb:movie:634492",
      source: "tmdb",
      sourceId: "634492",
      mediaType: "movie",
      title: "Madame Web",
      posterPath: "https://image.tmdb.org/t/p/w500/rULWuutDcN5NvtiZi4xZa35vY34.jpg",
      backdropPath: null,
      year: "2024",
      rating: 5.2,
      totalEpisodes: 1,
      genres: ["Action", "Sci-Fi"],
    },
    status: "dropped",
    userRating: "poor",
    updatedAt: "2024-03-01T10:00:00.000Z",
  },
  {
    id: "demo-14",
    media: {
      id: "tmdb:movie:693134",
      source: "tmdb",
      sourceId: "693134",
      mediaType: "movie",
      title: "Dune: Part Two",
      posterPath: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
      backdropPath: null,
      year: "2024",
      rating: 8.6,
      totalEpisodes: 1,
      genres: ["Sci-Fi", "Adventure"],
    },
    status: "watching",
    userRating: null,
    updatedAt: "2024-04-10T12:00:00.000Z",
  },
];
